CREATE TABLE [dbo].[SPIN_WEIGHT_TEMP]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [PRODUCT_DATA] NVARCHAR(8) NOT NULL, 
    [PLANT_ID] NVARCHAR(20) NOT NULL, 
    [LINE_ID] NVARCHAR(20) NOT NULL, 
    [POS] NVARCHAR(20) NOT NULL, 
    [END_ID] NVARCHAR(20) NOT NULL, 
    [LOT] NVARCHAR(20) NOT NULL, 
    [LOT_SEQ] NVARCHAR(20) NOT NULL, 
    [DOFF] INT NOT NULL, 
    [SIDE] NCHAR(20) NULL, 
    [USL] NUMERIC(15, 5) NULL, 
    [SL] NUMERIC(15, 5) NULL, 
    [LSL] NUMERIC(15, 5) NULL, 
    [UCL] NUMERIC(15, 5) NULL, 
    [CL] NUMERIC(15, 5) NULL, 
    [LCL] NUMERIC(15, 5) NULL, 
    [VALUE] NUMERIC(15, 5) NULL, 
    [MARK] NVARCHAR(20) NULL, 
    [DECISION_ID] NVARCHAR(20) NULL, 
    [SPEC_COLOR] NVARCHAR(10) NULL, 
    [CREATED_BY] NVARCHAR(20) NULL, 
    [CREATED_ON] DATETIME NULL, 
    [MODIFIED_BY] NVARCHAR(20) NULL, 
    [MODIFIED_ON] DATETIME NULL

)
