CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [PRODUCT_DATA] CHAR(8) NOT NULL, 
    [PLANT_ID] NVARCHAR(20) NOT NULL, 
    [LINE_ID] NVARCHAR(20) NOT NULL, 
    [POS] NVARCHAR(20) NOT NULL, 
    [LOT] NVARCHAR(20) NOT NULL, 
    [LOT_SEQ] NVARCHAR(20) NOT NULL, 
    [START_END] NVARCHAR(10) NOT NULL, 
    [SIDE] NVARCHAR(20) NULL, 
    [END_END] NVARCHAR(20) NULL, 
    [END_QTY] NVARCHAR(20) NULL, 
    [INSPECT_END] NVARCHAR(20) NULL, 
    [CANCEL_YN] NVARCHAR(20) NOT NULL, 
    [END_DATA] CHAR(8) NULL, 
    [CREATED_BY] NVARCHAR(20) NULL, 
    [CREATED_ON] DATETIME NULL, 
    [MODIFIED_BY] NVARCHAR(20) NULL, 
    [MODIFIED_ON] DATETIME NULL
)
