CREATE TABLE [dbo].[Table]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [PLANT_ID] NVARCHAR(20) NOT NULL, 
    [LINE_ID] NVARCHAR(20) NOT NULL, 
    [LINE_NAME] NVARCHAR(50) NULL, 
    [POS_QTY] INT NULL, 
    [USE_YN] NVARCHAR(20) NULL, 
    [SIDE_QTY] INT NULL, 
    [SIDE_END_QTY] INT NULL, 
    [PROJECT_ID] NVARCHAR(20) NULL, 
    [CREATED_BY] NVARCHAR(20) NULL, 
    [CREATED_ON] DATETIME NULL, 
    [MODIFIED_BY] NVARCHAR(20) NULL, 
    [CREATED_ON] DATETIME NULL
)
