CREATE TABLE [dbo].[Mst_End]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [PLANT_ID] NVARCHAR(20) NOT NULL, 
    [END_ID] NVARCHAR(20) NOT NULL, 
    [END_NAME] NVARCHAR(50) NULL, 
    [PRT_ORDER] INT NULL, 
    [CREATED_BY] NVARCHAR(20) NULL, 
    [MODIFIED_BY] NVARCHAR(20) NULL, 
    [CREATED_ON] DATETIME NULL, 
    [MODIFIED_ON] DATETIME NULL
)
